import mundoColorado from "@/assets/images/sci-mundo-colorado.png";
import { api } from "@/service/api";
import type { Metadata } from "next";
import Image from "next/image";
import "../globals.css";
import "./layout.css";
export const metadata: Metadata = {
  title: "Mundo Colorado | Login",
  description: "Generated by create next app",

  icons: ["https://socio.internacional.com.br/img/icon-32x32.png"],
};

export default async function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const res = await api.get("cms/conteudos/banners_intenacional");
  const background = res.data.result.find((item: any) =>
    item.tags.includes("Banners_onboarding-0")
  );

  return (
    <div className="sci-main">
      <div
        className="sci-login-image"
        style={{ backgroundImage: "url(" + background.imagem + ")" }}
      ></div>

      <div className="sci-login-container">
        <Image src={mundoColorado} alt="mundo colorado" className="sci-logo" />
        {children}
      </div>
    </div>
  );
}
//style="{ backgroundImage: 'url(' + background + ')' }"
