import { Wrapper } from "@/components/Wrapper";
import { Footer } from "@/components/footer/Fotter";
import { FooterPartners } from "@/components/footer/footerPartners/FooterPartners";
import { Header } from "@/components/header/Header";
import { montSerrat } from "@/styles/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mundo Colorado | Homologação",
  description: "Generated by create next app",

  icons: ["https://socio.internacional.com.br/img/icon-32x32.png"],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montSerrat.className}>
        <Wrapper>
         
          {children}
        </Wrapper>
      </body>
    </html>
  );
}
