import { Wrapper } from "@/components/Wrapper";
import { Footer } from "@/components/footer/Fotter";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mundo Colorado | Homologação",
  description: "Generated by create next app",

  icons: ["https://socio.internacional.com.br/img/icon-32x32.png"],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Wrapper>{children}</Wrapper>
        <Footer />
      </body>
    </html>
  );
}
